Default: &defaults
  user: satvikc
  password: Satvik((
  host: localhost
  port: 5432

Development:
  <<: *defaults
  database: imghost_dev
  poolsize: 10

Production:
  <<: *defaults
  database: imghost
  poolsize: 100
